GET http://localhost:3000/subscribers


###
GET http://localhost:3000/subscribers/
5f8b0581ad7ee436e833941f

###
POST  http://localhost:3000/subscribers
Content-Type: application/json

{
    "name" : "Saif Khan",
    "channel" : "Coding Garden"
}


###
DELETE  http://localhost:3000/subscribers/
5f8b0581ad7ee436e833941f
